### ISSUE TITLE
Random behavior in Oderk4 plugin (dev2 branch)

### ISSUE THREAD

**Issue by pabloriera** [pabloriera/lode#10]
The following test gives random results may be due to memory allocation and bad initialization.

When running from one terminal (lib directory):
`sclang -D lode.scd`

and in another (root directory)
`python3 lib/test.py`

The results are either nans in the variables of the equations, or Oderk4 skips a break that should have done because of this hardcoded destruction. Probably unit->c is not starting at 0 as requested.

```
    unit->c = unit->c + 1;
    Print("%d\n", unit->c);
    if (unit->c == 2)
      Oderk4_Dtor(unit);
```

**Comment by munshkr** [comment]
Hmm, I think I fixed some issues with memory allocation and how the filename string was being copied from parameters. Can you test it? It sounds ok on my end now (sounds like a "sine" oscillator)

**Comment by pabloriera** [comment]
Ok, now the code is more clear. In my machine, it stills works randomly. sometimes ends at the first call of next because a nan is detected.

**Comment by pabloriera** [comment]
Which supercollider version are you using?

**Comment by munshkr** [comment]
I pushed a new branch `double` where all floats were replaced with double. Can you try it?

**Comment by pabloriera** [comment]
I found the bug! It was on the python side. There was a dict that needed to be ordered! The problem was that there were random changes on how the equations were written en cpp. The fix is now pushed. I will try to merge this dev2 with dev1 branch
